# Generated by Django 5.2.14 on 2026-06-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbot",
            name="clone_feedback",
        ),
        migrations.RemoveField(
            model_name="chatbot",
            name="clone_verdict",
        ),
    ]
