# Generated by Django 5.2.14 on 2026-06-01 10:31

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatBot",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conv_id", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("route", models.CharField(default="general", max_length=16)),
                ("generated_sql", models.TextField(blank=True, null=True)),
                ("sql_result_raw", models.JSONField(blank=True, null=True)),
                ("clone_verdict", models.CharField(default="skipped", max_length=32)),
                ("clone_feedback", models.TextField(blank=True, null=True)),
                ("regeneration_count", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chatbot",
                "ordering": ["created_at"],
            },
        ),
    ]
