# Generated by Django 5.2.14 on 2026-06-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_remove_chatbot_clone_feedback_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbot",
            name="regeneration_count",
        ),
    ]
