# Generated by Django 5.2.14 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_chatbot_regeneration_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="visualizations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
