"""
Django settings for Ran Analytics project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@3+nikk-ye*6r6z!o&58rbvhya@qgqbhaap7=%)!h4_vkq*vu-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*","localhost","127.0.0.1"]


# Application definition

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "api",
#     "database"
# ]

INSTALLED_APPS = [
    "ran_analytics.apps.MongoAdminConfig",
    "ran_analytics.apps.MongoAuthConfig",
    "ran_analytics.apps.MongoContentTypesConfig",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_mongodb_backend",
    "corsheaders",
    "rest_framework",
    "api",
    "database",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "ran_analytics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ran_analytics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "HOST": "mongodb://localhost:27017",
        "NAME": "ran_analytics_db",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"




RCMS_DB = {
    "DRIVER": os.environ.get("RCMS_DB_DRIVER", "ODBC Driver 17 for SQL Server"),
    "SERVER": os.environ.get("RCMS_DB_SERVER", "localhost"),
    "DATABASE": os.environ.get("RCMS_DB_NAME", "SchemaSnapshot"),
    "USER": os.environ.get("RCMS_DB_USER", ""),
    "PASSWORD": os.environ.get("RCMS_DB_PASSWORD", ""),
    "TRUSTED": os.environ.get("RCMS_DB_TRUSTED", "yes"),
}

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4.1")
CHATBOT_MAX_RETRIES = int(os.environ.get("CHATBOT_MAX_RETRIES", "2"))
CHATBOT_MAX_ROWS_TO_LLM = int(os.environ.get("CHATBOT_MAX_ROWS_TO_LLM", "50"))
CHATBOT_SCHEMA_CACHE_TTL = int(os.environ.get("CHATBOT_SCHEMA_CACHE_TTL", "300"))
CHATBOT_MAX_HISTORY_TURNS = int(os.environ.get("CHATBOT_MAX_HISTORY_TURNS", "8"))
CHATBOT_HISTORY_ROW_PREVIEW = int(os.environ.get("CHATBOT_HISTORY_ROW_PREVIEW", "3"))
CHATBOT_CHART_MAX_POINTS = int(os.environ.get("CHATBOT_CHART_MAX_POINTS", "10"))
CHATBOT_SCHEMA_DOCS_PATH = os.environ.get(
    "CHATBOT_SCHEMA_DOCS_PATH",
    str(BASE_DIR / "data" / "schema_descriptions.json"),
)
CHATBOT_SCHEMA_DOCS_CACHE_TTL = int(os.environ.get("CHATBOT_SCHEMA_DOCS_CACHE_TTL", "3600"))